export {default as Header } from './common/header'
export {default as Logo } from './common/logo'
export {default as SignUp } from './pages/signup'
export {default as Login } from './pages/login'
export {default as Landing } from './pages/landing'
export {default as Footer } from './common/footer'
export {default as FAQ } from './pages/faq'
export {default as Appointments } from './pages/appointments'
export {default as Dashboard } from './pages/dashboard'
export {default as Profile } from './pages/profile'
export {default as Placement} from './pages/placement'
export {default as StudentCourseApproval} from './pages/studentCourseApproval'
export {default as StudentCourseRequest } from './pages/request'
export {default as CoordinatorApproval } from './pages/coordinatorAppointmentApproval'
export {default as Error } from './pages/error'
