export {default as CourseRoute } from './GenericRoutes/CourseRoute'
export {default as StageRoute } from './GenericRoutes/StageRoute'
export {default as AppointmentRoute } from './GenericRoutes/AppointmentRoute'
export {default as AdminRoute } from './AdminRoutes'
export {default as PlacementListRoute } from './GenericRoutes/PlacementListRoute'
export {default as PlacementRoute } from './GenericRoutes/PlacementRoute'